export type EpisodeScript = {
  n: number;
  title: string;
  tagline: string;
  video: string;
  pdf: string;
  scriptFile: string;
  pages: string[];
  voiceover: string;
};

export const EPISODE_SCRIPTS: EpisodeScript[] = [
  {
    n: 0,
    title: "What is the cloud?",
    tagline: "Not weather. A town of helpers in the sky.",
    video: "/00-What-is-the-cloud.mp4?v=native9x16",
    pdf: "/scripts/00-What-is-the-cloud-script.pdf",
    scriptFile: "00-What-is-the-cloud-script.pdf",
    pages: ["/script-pages/00-What-is-the-cloud-script-p1.jpg"],
    voiceover: "Welcome! This is Maya. She is at home, on the ground, playing a game on her tablet. But wait. Where does the game live? Not in the tablet. Look up! We fly through the real clouds. A town is floating in the sky. Cream houses. Teal lamps. The cloud is not weather. It is a town of helpers, high in the sky, that keeps your stuff and runs your games. That chest keeps things. That computer runs things. That little spark pops in for one job. Maya taps play. A tiny light flies from her tablet, up to the town, and back. The game loads! The cloud is a town of helpers in the sky. Now you know the cloud! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 1,
    title: "The helpers",
    tagline: "Sammy stores. Eddie runs. Lulu pops in.",
    video: "/01-The-helpers.mp4?v=9x16",
    pdf: "/scripts/01-The-helpers-script.pdf",
    scriptFile: "01-The-helpers-script.pdf",
    pages: ['/script-pages/01-The-helpers-script-p1.jpg', '/script-pages/01-The-helpers-script-p2.jpg'],
    voiceover: "Welcome to Cloud Town, high up in the sky! Meet Sammy the Super Storage Box. Sammy is S3. He keeps photos, toys, and files safe forever. Here's Eddie. Eddie is EC2, a computer who never sleeps. He runs websites and games all day long. And this is Lulu. Lulu is Lambda. She pops in, does one job super fast, then poofs away. Together they make the cloud work. Now you know AWS!",
  },
  {
    n: 2,
    title: "Sammy\u2019s closet",
    tagline: "Buckets, shelves, and the whole freezer family.",
    video: "/02-Sammys-closet.mp4?v=9x16",
    pdf: "/scripts/02-Sammy-s-closet-script.pdf",
    scriptFile: "02-Sammy-s-closet-script.pdf",
    pages: ['/script-pages/02-Sammy-s-closet-script-p1.jpg', '/script-pages/02-Sammy-s-closet-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 2. Meet Sammy the Super Storage Box. Sammy is S3. His closet is a bucket. Each drawing is an object. He never fills up. The everyday shelf is S3 Standard. You can open it any time. The dusty shelf is Infrequent Access. It is cheaper if you do not peek every day. One Zone-IA lives in just one yard. Intelligent-Tiering is a magic closet. It moves drawings to cheaper shelves by itself. Glacier Instant is a chilly drawer you can open right now. Glacier Flexible Retrieval waits a little. Glacier Deep Archive sleeps for years. Now you know Sammy's closet!",
  },
  {
    n: 3,
    title: "Copies and locks",
    tagline: "Versioning, copies across towns, and doors that stay shut.",
    video: "/03-Copies-and-locks.mp4?v=9x16",
    pdf: "/scripts/03-Copies-and-locks-script.pdf",
    scriptFile: "03-Copies-and-locks-script.pdf",
    pages: ['/script-pages/03-Copies-and-locks-script-p1.jpg', '/script-pages/03-Copies-and-locks-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 3. Sammy keeps old drawings too. Versioning keeps the old drawing when you paint a new one. A lifecycle rule tucks old drawings into the freezer by itself. Sammy copies treasures into many buildings. Eleven nines means they almost never vanish. Cross-Region Replication sends a copy to another Cloud Town. Encryption is a padlock on the closet. Block Public Access keeps strangers out. Object Lock says this drawing may not be erased. Old drawings stay. Copies fly. Locks stay shut. Now you know copies and locks!",
  },
  {
    n: 4,
    title: "The neighborhood",
    tagline: "A fence, a front street, a backyard, and a tunnel home.",
    video: "/04-The-neighborhood.mp4?v=ana",
    pdf: "/scripts/04-The-neighborhood-script.pdf",
    scriptFile: "04-The-neighborhood-script.pdf",
    pages: ['/script-pages/04-The-neighborhood-script-p1.jpg', '/script-pages/04-The-neighborhood-script-p2.jpg', '/script-pages/04-The-neighborhood-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Meet Vivi the fence. A VPC is our own private neighborhood. Front street is public. The backyard is private. Iggie is the Internet Gateway, the big front gate! Albie the doorman greets visitors on the public street. Eddie the computer and Dot the vault hide in the backyard. Nat the mail window lets Eddie go out, but strangers cannot come in. That's egress! A sky bridge links another town. A secret tunnel reaches a house on the ground. Now you know the neighborhood! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 5,
    title: "The other boxes",
    tagline: "A backpack, a fridge, fancy cupboards, a door at home, and a spare.",
    video: "/05-The-other-boxes.mp4?v=ana",
    pdf: "/scripts/05-The-other-boxes-script.pdf",
    scriptFile: "05-The-other-boxes-script.pdf",
    pages: ['/script-pages/05-The-other-boxes-script-p1.jpg', '/script-pages/05-The-other-boxes-script-p2.jpg', '/script-pages/05-The-other-boxes-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 5. Sammy the Super Storage Box has a surprise. He has more than one closet! First, meet Eddie's backpack disk. That is EBS. It belongs to one Eddie and travels with him. Next, the shared fridge. That is EFS. Many Eddies can open it at the same time. These fancy cupboards are FSx. Way in the back is the deep freezer. That is S3 Glacier. Old drawings sleep here. It is cheap, and slow to open. A little door at home is Storage Gateway. And this is Backup, the spare-copy machine. Now you know Sammy's closets! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 6,
    title: "The key keepers",
    tagline: "Name tags, school badges, guest stickers, and a shared swing.",
    video: "/06-The-key-keepers.mp4?v=9x16",
    pdf: "/scripts/06-The-key-keepers-script.pdf",
    scriptFile: "06-The-key-keepers-script.pdf",
    pages: ['/script-pages/06-The-key-keepers-script-p1.jpg', '/script-pages/06-The-key-keepers-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 6. A town with no keys is not safe. A town with one shared key is not safe either. Meet the key ring. That is IAM. Users have name tags. Groups are a whole class. A role is a badge you borrow for one job. A policy is the list of may and may-not. Identity Center is one school badge that opens many classrooms. Cognito is a guest sticker for friends who do not live here. Directory Service brings the old class list into the sky. RAM shares a swing, not the house key. Now you know the key keepers!",
  },
  {
    n: 7,
    title: "The key ring",
    tagline: "User, role, policy, SCP, and STS.",
    video: "/07-The-key-ring.mp4?v=9x16",
    pdf: "/scripts/07-The-key-ring-script.pdf",
    scriptFile: "07-The-key-ring-script.pdf",
    pages: ['/script-pages/07-The-key-ring-script-p1.jpg', '/script-pages/07-The-key-ring-script-p2.jpg', '/script-pages/07-The-key-ring-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 7. Today we open the key ring all the way. That is IAM. A user is a kid with a name tag. That kid lives in town. A role is a badge you borrow for one job, then you give it back. A policy is the list of may and may-not on the door. An SCP is the principal's rule. No classroom may break it, even if a teacher says yes. STS is a visitor pass that peels off at sunset. You borrow keys for a little while, then they vanish. Name tag. Borrowed badge. Door list. Principal's rule. Sunset pass. Now you know IAM!",
  },
  {
    n: 8,
    title: "The school badge",
    tagline: "One badge, many classrooms \u2014 not a name tag, not a guest sticker.",
    video: "/08-The-school-badge.mp4?v=9x16",
    pdf: "/scripts/08-The-school-badge-script.pdf",
    scriptFile: "08-The-school-badge-script.pdf",
    pages: ['/script-pages/08-The-school-badge-script-p1.jpg', '/script-pages/08-The-school-badge-script-p2.jpg', '/script-pages/08-The-school-badge-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 8. The school badge is IAM Identity Center. One badge opens many classrooms. The office picks the class list. That is the identity source. Cloud Town's own list, the old class list, or another school. A permission set is which rooms the badge opens. Each classroom is an AWS account. You sign in once. This is not an IAM name tag. A name tag only works in one house. This is not a Cognito guest sticker. Guest stickers are for lemonade. The school badge is for the whole school. Now you know Identity Center!",
  },
  {
    n: 9,
    title: "The guest sticker",
    tagline: "User pools, identity pools, lemonade guests \u2014 not town workers.",
    video: "/09-The-guest-sticker.mp4?v=9x16",
    pdf: "/scripts/09-The-guest-sticker-script.pdf",
    scriptFile: "09-The-guest-sticker-script.pdf",
    pages: ['/script-pages/09-The-guest-sticker-script-p1.jpg', '/script-pages/09-The-guest-sticker-script-p2.jpg', '/script-pages/09-The-guest-sticker-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 9. Meet the guest sticker. That is Amazon Cognito. It is for friends who buy lemonade, not for kids who work in town. A user pool is the lemonade club list. Guests sign up and get a sticker. An identity pool is a tray of sunset passes. A guest can peek at one drawing, then the pass peels off. That uses STS. You can sign in at the lemonade window. Or use a badge from another playground. This is not IAM. A name tag is for workers. This is not Identity Center. A school badge is for the whole school. Cognito is for the lemonade stand. Now you know Cognito!",
  },
  {
    n: 10,
    title: "The vaults",
    tagline: "Pick the vault that matches the treasure.",
    video: "/10-The-vaults.mp4?v=9x16",
    pdf: "/scripts/10-The-vaults-script.pdf",
    scriptFile: "10-The-vaults-script.pdf",
    pages: ['/script-pages/10-The-vaults-script-p1.jpg', '/script-pages/10-The-vaults-script-p2.jpg', '/script-pages/10-The-vaults-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 10. Meet Dot. She is a vault. But Dot is not only one vault. RDS is a tidy notebook. AWS turns the pages. Aurora is the super notebook. Extra copies. Extra fast. Aurora Serverless wakes when you write, then naps. DynamoDB is labeled cubbies. Grab by name. Super fast. ElastiCache is the snack already unwrapped. DocumentDB keeps JSON stories. Neptune is a family tree. Keyspaces are wide cubbies. Pick the vault that matches the treasure. Now you know the vaults!",
  },
  {
    n: 11,
    title: "The tidy notebook",
    tagline: "AWS turns the pages.",
    video: "/11-The-tidy-notebook.mp4?v=9x16",
    pdf: "/scripts/11-The-tidy-notebook-script.pdf",
    scriptFile: "11-The-tidy-notebook-script.pdf",
    pages: ['/script-pages/11-The-tidy-notebook-script-p1.jpg', '/script-pages/11-The-tidy-notebook-script-p2.jpg', '/script-pages/11-The-tidy-notebook-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 11. RDS is Amazon RDS. A tidy notebook with rows and columns. AWS turns the pages. You pick the brand. MySQL. PostgreSQL. And more. Eddie asks Dot in the backyard. Visitors never meet her. That is a private street. If one notebook gets sleepy, a spare waits in the other yard. That is Multi-AZ. A reading copy keeps the line short. That is a replica. At night, AWS photocopies the pages. Those are backups. AWS does the grown-up jobs. Now you know RDS!",
  },
  {
    n: 12,
    title: "The super notebook",
    tagline: "Extra copies. Extra fast. Then it naps.",
    video: "/12-The-super-notebook.mp4?v=9x16",
    pdf: "/scripts/12-The-super-notebook-script.pdf",
    scriptFile: "12-The-super-notebook-script.pdf",
    pages: ['/script-pages/12-The-super-notebook-script-p1.jpg', '/script-pages/12-The-super-notebook-script-p2.jpg', '/script-pages/12-The-super-notebook-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 12. RDS is a tidy notebook. Aurora is the super notebook. Extra copies. Extra fast. It still speaks MySQL. It still speaks PostgreSQL. All the notebooks share one big pile of pages. Write once. Everyone can read. Extra copies help the line stay short. Those are replicas. They share the same pile. When nobody writes, Aurora Serverless takes a nap. When Eddie writes, it wakes up. AWS grows the pages. Now you know Aurora!",
  },
  {
    n: 13,
    title: "The nap",
    tagline: "Sleeps when empty. Grows for a crowd. You pay for a sip.",
    video: "/13-The-nap.mp4?v=9x16",
    pdf: "/scripts/13-The-nap-script.pdf",
    scriptFile: "13-The-nap-script.pdf",
    pages: ['/script-pages/13-The-nap-script-p1.jpg', '/script-pages/13-The-nap-script-p2.jpg', '/script-pages/13-The-nap-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 13. Aurora can stay wide awake. That is provisioned. Or Aurora can nap. That is Aurora Serverless. When the lemonade stand is empty, the notebook sleeps. You do not pay for a whole pitcher. You pay for a sip. When a crowd comes, it wakes and grows. ACU is how wide the pages get. Lulu pops in for one job, then she is gone. This notebook stays. It just takes a nap. Still MySQL. Still PostgreSQL. Same pile of pages. Now you know Aurora Serverless!",
  },
  {
    n: 14,
    title: "The labeled cubbies",
    tagline: "Grab by name. Super fast. No rows to turn.",
    video: "/14-The-labeled-cubbies.mp4?v=9x16",
    pdf: "/scripts/14-The-labeled-cubbies-script.pdf",
    scriptFile: "14-The-labeled-cubbies-script.pdf",
    pages: ['/script-pages/14-The-labeled-cubbies-script-p1.jpg', '/script-pages/14-The-labeled-cubbies-script-p2.jpg', '/script-pages/14-The-labeled-cubbies-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 14. RDS is a tidy notebook. Aurora is a super notebook. You turn pages. DynamoDB is labeled cubbies. Grab by name. Super fast. No rows to turn. Eddie already knows the name. He does not hunt through a notebook. The name on the cubby is the partition key. The order inside is the sort key. When a cubby changes, a whisper goes out. That is a stream. Extra labels help you find things another way. Those are GSIs. Always on. No nap needed. Now you know DynamoDB!",
  },
  {
    n: 15,
    title: "The cubby extras",
    tagline: "DAX, twin towns, paying for grabs, now vs in a moment.",
    video: "/15-The-cubby-extras.mp4?v=9x16",
    pdf: "/scripts/15-The-cubby-extras-script.pdf",
    scriptFile: "15-The-cubby-extras-script.pdf",
    pages: ["/script-pages/15-The-cubby-extras-script-p1.jpg", "/script-pages/15-The-cubby-extras-script-p2.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 15. DynamoDB is labeled cubbies. Here are the extras. DAX is a snack shelf only for cubbies. Repeats come instantly. You do not open the cubby every time. Global tables are the same cubbies in another town. Write here. It shows up there. Friends far away see the same toys. On-demand means you pay per grab. One coin for one lemon. Provisioned means you save a line for busy days. A strong read is now. An eventual read is in a moment. Now you know the cubby extras! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 16,
    title: "The unwrapped snack",
    tagline: "ElastiCache. Redis or Memcached. Not the vault.",
    video: "/16-The-unwrapped-snack.mp4?v=9x16",
    pdf: "/scripts/16-The-unwrapped-snack-script.pdf",
    scriptFile: "16-The-unwrapped-snack-script.pdf",
    pages: ["/script-pages/16-The-unwrapped-snack-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 16. Repeats should not knock on the vault every time. Eddie can grab a snack instead. ElastiCache is the unwrapped snack. Redis or Memcached. A snack already open. Redis can remember a list. Memcached is a simple tray. If the snack tray tips, the real notebook still has the recipe. Dot is safe. The snack is not the vault. DAX is a snack only for cubbies. ElastiCache can sit in front of notebooks too. Hot reads come instantly. Now you know the unwrapped snack! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 17,
    title: "The story vault",
    tagline: "DocumentDB. A whole tale as one pile of pages.",
    video: "/17-The-story-vault.mp4?v=9x16",
    pdf: "/scripts/17-The-story-vault-script.pdf",
    scriptFile: "17-The-story-vault-script.pdf",
    pages: ["/script-pages/17-The-story-vault-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 17. Dot has a tidy notebook. Rows and columns. The cubbies grab by name. The story vault is different. DocumentDB keeps a whole tale as one pile of pages. Like a storybook. Name, pictures, and notes stay together. You do not split the tale into rows. You do not need the same boxes on every page. It talks like MongoDB. Eddie can read the whole story at once. If a page is missing, the tale still makes sense. Now you know the story vault! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 18,
    title: "The family tree",
    tagline: "Neptune. Who is related to who. That is a graph.",
    video: "/18-The-family-tree.mp4?v=9x16",
    pdf: "/scripts/18-The-family-tree-script.pdf",
    scriptFile: "18-The-family-tree-script.pdf",
    pages: ["/script-pages/18-The-family-tree-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 18. Dot has rows. Cubbies grab by name. The story vault is a pile of pages. Neptune is the family tree. It does not store a list. It stores who is related to who. Maya is friends with Eddie. Eddie is friends with Lulu. The tree shows the whole web. You ask, who knows who? Super fast. A list would take forever. The tree already knows the path. Friends of friends light up too. That is a graph. Now you know the family tree! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 19,
    title: "The wide cubbies",
    tagline: "Keyspaces. Cassandra-style. One name, a long row of slots.",
    video: "/19-The-wide-cubbies.mp4?v=9x16",
    pdf: "/scripts/19-The-wide-cubbies-script.pdf",
    scriptFile: "19-The-wide-cubbies-script.pdf",
    pages: ["/script-pages/19-The-wide-cubbies-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 19. Dynamo cubbies grab by name. One toy per cubby. Keyspaces is wide cubbies. One name, then a long row of slots. Like Cassandra. A whole week of drawings stay in one wide cubby. You can peek a slice. You do not hunt the whole town. Eddie talks Cassandra talk. AWS keeps the house. You do not build it yourself. Many towns can share the wide cubbies. Super wide. Super fast. Now you know the wide cubbies! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 20,
    title: "The toy boxes",
    tagline: "Boxy, Kira, and Fay. Many Eddies in boxes.",
    video: "/20-The-toy-boxes.mp4?v=story",
    pdf: "/scripts/20-The-toy-boxes-script.pdf",
    scriptFile: "20-The-toy-boxes-script.pdf",
    pages: ["/script-pages/20-The-toy-boxes-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya's class all tap play at once. Twenty games! One Eddie cannot do it. He wobbles. Toys drop. Boxy opens! Little Eddies pop out and run the jobs. Boxy is ECS. A toy box that runs many Eddies. Tweet! Kira blows her whistle. Five Boxys line up in a row. Kira is EKS. The captain of the toy boxes. Whoosh! Fay flies a box up to a house. No Eddie under it! Fay is Fargate. She flies. No Eddie has to hold the box. The games load. All twenty! Maya cheers. Now you know the toy boxes! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 21,
    title: "Boxy",
    tagline: "ECS. One box. Many jobs. If a little Eddie stops, Boxy pops a new one in.",
    video: "/21-Boxy.mp4?v=story",
    pdf: "/scripts/21-Boxy-script.pdf",
    scriptFile: "21-Boxy-script.pdf",
    pages: ["/script-pages/21-Boxy-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has many tiny jobs. Wrap this. Carry that. Tap this. One Eddie cannot hold them all. Into Boxy they go! One box. Many little Eddies pop out and run every job. That is ECS. A toy box that runs many Eddies. Oh no! One little Eddie inside stops. That one job goes dark. Maya's toy freezes. Boxy sees it. Pop! A new little Eddie jumps in. The job lights up again. The box keeps the jobs running. Now you know Boxy! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 22,
    title: "Kira",
    tagline: "EKS. The captain of the toy boxes. The whole row works in step.",
    video: "/22-Kira.mp4?v=story",
    pdf: "/scripts/22-Kira-script.pdf",
    scriptFile: "22-Kira-script.pdf",
    pages: ["/script-pages/22-Kira-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has five Boxys. Each one does its own thing. Toys everywhere! Nothing lines up. Kira is the captain of the toy boxes. Tweet! She blows her whistle. The boxes line up. This box wraps. That box carries. That box taps. Oh no! One box tips over. Kira puts a new box in its place. The line gets long. Kira adds one more. Now the whole row works in step. That is EKS. Now you know Kira! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 23,
    title: "Fay",
    tagline: "Fargate. She flies the box. No Eddie underneath.",
    video: "/23-Fay.mp4?v=story",
    pdf: "/scripts/23-Fay-script.pdf",
    scriptFile: "23-Fay-script.pdf",
    pages: ["/script-pages/23-Fay-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has a box of jobs. Wrap this. Carry that. Tap this. But every Eddie in town is busy. Nobody can carry the box. Look: Boxy sits on Eddie's head. Boxy needs an Eddie. Whoosh! Fay flies in. She is a flying box. She carries the jobs herself. No Eddie underneath! The jobs run while she flies. When the jobs are done, Fay lands and rests. Eddie can go play. Nobody pays for an Eddie that sits idle. That is Fargate. Now you know Fay! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 24,
    title: "The front door",
    tagline: "Mapi points. Zip copies at the edge. Boost is one fast door.",
    video: "/24-The-front-door.mp4?v=story",
    pdf: "/scripts/24-The-front-door-script.pdf",
    scriptFile: "24-The-front-door-script.pdf",
    pages: ["/script-pages/24-The-front-door-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Remy is a visitor from far away. He wants to see Maya's drawing. He gets lost on the path. Then he arrives so slow. Oh no! Mapi is the town map. She is a signpost. She points him to the right house. Zip is the fast road. A copy of the drawing waits at the edge of town. Remy does not walk all the way in. He gets it right there. Boost is the rocket path. One front door. Always the fastest road, no matter where he starts. Remy smiles at the drawing. Now you know the front door! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 25,
    title: "Mapi",
    tagline: "Route 53. She points by name, not by color. That is failover.",
    video: "/25-Mapi.mp4?v=mapi2",
    pdf: "/scripts/25-Mapi-script.pdf",
    scriptFile: "25-Mapi-script.pdf",
    pages: ["/script-pages/25-Mapi-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Eddie, Sammy, and Lulu want to visit Maya. Oh no! Two houses look the same color. They knock on the wrong door. Mapi is the town map. She gives each house a name. A star. A moon. Not the color. The name! She points by name. This way to Maya. Oh no! Maya's house is closed. Mapi points to the open twin. That is failover. All three friends at the right door. Maya waves. Now you know Mapi! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 26,
    title: "Zip",
    tagline: "CloudFront. A copy waits at the edge of town.",
    video: "/26-Zip.mp4?v=cream",
    pdf: "/scripts/26-Zip-script.pdf",
    scriptFile: "26-Zip-script.pdf",
    pages: ["/script-pages/26-Zip-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Remy lives far away. He wants Maya's new drawing. Sammy walks it all the way across town. Remy waits. And waits. And waits. So slow! The first trip takes forever. Zip is the fast road. Zip keeps a copy at the edge of town, near Remy. Next time Remy asks... it is right there! Instant! Maya paints a new drawing. The old copy goes away. Zip fetches the fresh one. Remy smiles. Maya waves. Now you know Zip! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 27,
    title: "Boost",
    tagline: "Global Accelerator. One door. Always the fastest road.",
    video: "/27-Boost.mp4?v=teal",
    pdf: "/scripts/27-Boost-script.pdf",
    scriptFile: "27-Boost-script.pdf",
    pages: ["/script-pages/27-Boost-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya's friends want to visit. They live far away. Each one picks a different road. One road is bumpy. One bridge is closed. One road is long. They arrive late. And tired. Boost is one front door. A glowing doorway at the edge of the sky. Every visitor goes to Boost first. Boost sends each one down the fastest road. Zip keeps copies near you. Boost gives you one door, and the fastest road. They all arrive fast. Maya waves. Now you know Boost! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 28,
    title: "The name tag on the door",
    tagline: "ACM, API Gateway, Amplify. Lock, tickets, and a booth that pops up.",
    video: "/28-The-name-tag-on-the-door.mp4?v=p2",
    pdf: "/scripts/28-The-name-tag-on-the-door-script.pdf",
    scriptFile: "28-The-name-tag-on-the-door-script.pdf",
    pages: ["/script-pages/28-The-name-tag-on-the-door-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya wants a lemonade stand for visitors. Oh no! A visitor is scared. Is this a fake stand? A crowd shouts all at once. Building the stand by hand takes forever. Seal is the lock on the door. She glows. This is really Maya's house. The visitor relaxes. Winn is the ticket window. She hands tickets in order. Too many? She holds up a hand. Wait. Poppy is the booth kit. One pop! The whole stand is ready. Happy visitors in a tidy line. Maya waves. Now you know the name tag on the door! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 29,
    title: "Seal",
    tagline: "ACM. Look for the glow before you hand over your coin.",
    video: "/29-Seal.mp4?v=face",
    pdf: "/scripts/29-Seal-script.pdf",
    scriptFile: "29-Seal-script.pdf",
    pages: ["/script-pages/29-Seal-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Remy walks up to a lemonade stand. It looks like Maya's. Oh no! The awning is crooked. It is a copycat. Remy almost hands over his coin. Seal is the lock sticker. Only Maya's real door has her. Seal glows. The copycat has no glow. Remy walks past the fake. He buys at the real one. Look for the glow before you hand over your coin. Seal gets tired. The glow fades. A fresh Seal pops on, all by herself. Remy has lemonade. Maya waves. Now you know Seal! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 30,
    title: "Winn",
    tagline: "API Gateway. Ask at the window, get a ticket, wait your turn.",
    video: "/30-Winn.mp4?v=rect",
    pdf: "/scripts/30-Winn-script.pdf",
    scriptFile: "30-Winn-script.pdf",
    pages: ["/script-pages/30-Winn-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Helpers work in the back. Sammy has photos. Eddie mixes. Lulu scoops ice. Oh no! Visitors walk into the back. Eddie drops a pitcher. Winn is the ticket window. Come to the window first. Ask nicely. Get a ticket. Winn passes it to the right helper. Helpers are calm. A crowd rushes. Winn holds up a hand. Wait. A few at a time. No ticket? Winn shakes her head. Seal glows. Only real friends get in. Ask at the window, get a ticket, wait your turn. Maya waves. Now you know Winn! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 31,
    title: "Poppy",
    tagline: "Amplify. Build the front once, and it pops up for everyone.",
    video: "/31-Poppy.mp4?v=1",
    pdf: "/scripts/31-Poppy-script.pdf",
    scriptFile: "31-Poppy-script.pdf",
    pages: ["/script-pages/31-Poppy-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 31. Maya wants her lemonade stand today. She hammers one board. Then another. It takes forever. The door is not joined to the window. Nothing works yet. Oh no! Here comes the booth kit. One pop! The street, the door, and the window unfold together. Already joined. Already ready. Maya draws a new picture. The kit sends it to every stand in town. No hammering. No waiting. Build the front once, and it pops up for everyone. Now you know Amplify! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 32,
    title: "The post office",
    tagline: "SQS, SNS, EventBridge. A line, one call, the right chute.",
    video: "/32-The-post-office.mp4?v=1",
    pdf: "/scripts/32-The-post-office-script.pdf",
    scriptFile: "32-The-post-office-script.pdf",
    pages: ["/script-pages/32-The-post-office-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 32. Maya wants to invite all her friends to a party. She shouts. Everyone talks at once. Nobody hears. She hands out notes one by one. One note falls in a puddle. The post office can help. The letter box holds every note in a neat line. First in, first out. Nothing gets lost. The town horn calls once. Every friend hears at the same moment. The sorting table sends the round parcel down the round chute and the square one down the square chute. Quiet street. Every friend told. Nothing lost. Now you know the post office! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 33,
    title: "Pip",
    tagline: "SQS. Notes wait in a neat line. First in, first out.",
    video: "/33-Pip.mp4?v=catch",
    pdf: "/scripts/33-Pip-script.pdf",
    scriptFile: "33-Pip-script.pdf",
    pages: ["/script-pages/33-Pip-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 33. Maya has a note for Eddie. But Eddie is not home. She waits. And waits. Oh no! The wind takes her note away. Here comes the letter box. Maya drops her notes inside. Red, then yellow, then blue. They wait in a neat line. Nothing blows away. Maya does not have to wait. She goes to play. Eddie comes home. He opens the flap. Red first. Then yellow. Then blue. The same order they went in. Every note is safe. Every note is read. That is the letter box. Now you know SQS! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 34,
    title: "Hoot",
    tagline: "SNS. Say it once, and every friend hears.",
    video: "/34-Hoot.mp4?v=1",
    pdf: "/scripts/34-Hoot-script.pdf",
    scriptFile: "34-Hoot-script.pdf",
    pages: ["/script-pages/34-Hoot-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 34. Maya made lemonade. She wants to tell Sammy, Eddie and Lulu. She runs to one house. Then the next. Then the next. Oh no! Sammy wandered off. Eddie never heard. Here comes the town horn. Maya taps the post once. The horn calls one time. Sammy hears it. Eddie hears it. Lulu hears it. All at the same moment. Everyone comes running. Maya does not run anymore. Say it once, and every friend hears it. That is the town horn. Now you know SNS! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 35,
    title: "Tilly",
    tagline: "EventBridge. Right thing, right friend, every time.",
    video: "/35-Tilly.mp4?v=1",
    pdf: "/scripts/35-Tilly-script.pdf",
    scriptFile: "35-Tilly-script.pdf",
    pages: ["/script-pages/35-Tilly-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 35. A big pile of parcels lands in the street. Round ones. Square ones. Triangle ones. All mixed up. Maya carries them one at a time. Oh no! She gives a square to Sammy. Wrong friend. Here comes the sorting table. Maya dumps the whole pile on top. The lever flips. Round goes down the round chute to Sammy. Square goes down the square chute to Eddie. Triangle goes down the triangle chute to Lulu. Right thing, right friend. Now you know EventBridge! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 36,
    title: "Tess",
    tagline: "Step Functions. One step at a time. Each step waits for the one before.",
    video: "/36-Tess.mp4?v=vo2",
    pdf: "/scripts/36-Tess-script.pdf",
    scriptFile: "36-Tess-script.pdf",
    pages: ["/script-pages/36-Tess-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 36. Maya needs three jobs done. Cups first. Then mixing. Then pouring. She claps once. Everyone starts at the same time. Oh no! Lulu pours lemonade into thin air. No cups yet. What a mess. Here comes the staircase. Sammy stands on the first step. It lights up. He sets out the cups. Now the second step lights. Eddie mixes the jug. Now the third step lights. Lulu pours. Every cup is full. The flag pops up at the top. One step at a time. Each step waits for the one before it. That is the staircase. Now you know Step Functions! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 37,
    title: "Mira",
    tagline: "AppSync. Draw it once, everyone sees it right now.",
    video: "/37-Mira.mp4?v=1",
    pdf: "/scripts/37-Mira-script.pdf",
    scriptFile: "37-Mira-script.pdf",
    pages: ["/script-pages/37-Mira-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 37. Maya draws a sun. She wants everyone to see it. She runs to Sammy. Then to Eddie. Then to Lulu. Oh no! She changes her mind and draws a star. Now she has to run all over again. Here comes the drawing board. Every friend gets a little board of their own. Maya draws a heart on the big one. Pop! The same heart shows up on all three. She draws a star. Every board changes at once. Nobody runs. Draw it once, everyone sees it right now. That is the drawing board. Now you know AppSync! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 57,
    title: "The glow string",
    tagline: "X-Ray. Follow the path. Find the slow spot. Fix it.",
    video: "/57-The-glow-string.mp4?v=1",
    pdf: "/scripts/57-The-glow-string-script.pdf",
    scriptFile: "57-The-glow-string-script.pdf",
    pages: [],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 57. Maya's line is slow. Every cup takes forever. But why? Oh no! Here comes the glow string. It ties onto a lemon. And follows it. Into the squeezer. Orange! Thick! Squeak, squeak. Slow here! Into the pitcher. Yellow. Fast. Into the cup. Yellow. Fast. To the friend. Yellow. Fast. Only one slow spot. The squeezer! Maya gets a big new one. Whoosh! Now the string is yellow everywhere. The line moves fast. Follow the path. Find the slow spot. Fix it. That is the glow string. Now you know X-Ray! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 58,
    title: "The builder crew",
    tagline: "Auto Scaling, Beanstalk, Batch, ECR. Four helpers, one busy stand.",
    video: "/58-The-builder-crew.mp4?v=1",
    pdf: "/scripts/58-The-builder-crew-script.pdf",
    scriptFile: "58-The-builder-crew-script.pdf",
    pages: [],
    voiceover: "Oh no! Too many friends! Maya's stand can't keep up! Welcome back to Cloud Town, high up in the sky! This is Episode 58. Meet the builder crew. First, the copy stands. More friends? Pop, pop, pop! More stands. Fewer friends? They sink away. That is Auto Scaling. Next, the magic bean. Plant it, and whoosh, a whole stand is ready. Maya just makes lemonade. That is Beanstalk. At night, the night basket squeezes a mountain of lemons while Maya sleeps. That is Batch. And the toy shelf keeps the same lunchbox recipe for every stand. Every cup tastes the same. That is ECR. Four helpers, one busy stand. Now you know the builder crew! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 59,
    title: "The copy stands",
    tagline: "Auto Scaling. More friends, more stands. Fewer friends, fewer stands.",
    video: "/59-The-copy-stands.mp4?v=1",
    pdf: "/scripts/59-The-copy-stands-script.pdf",
    scriptFile: "59-The-copy-stands-script.pdf",
    pages: [],
    voiceover: "Oh no! A giant crowd! One stand is not enough! Welcome back to Cloud Town, high up in the sky! This is Episode 59. Meet the copy stands. The line gets long. Pop! A copy stand. Pop, pop! Two more. Now every friend gets a cup fast. Evening comes. The friends go home. The copy stands sink away. No empty stands. There is always one stand. And never more than the square can fit. Uh-oh, one copy stand is wobbly. It sinks, and a fresh one pops up. More friends, more stands. Fewer friends, fewer stands. That is the copy stands. Now you know Auto Scaling! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 60,
    title: "The magic bean",
    tagline: "Elastic Beanstalk. You bring the lemon. The bean builds the rest.",
    video: "/60-The-magic-bean.mp4?v=1",
    pdf: "/scripts/60-The-magic-bean-script.pdf",
    scriptFile: "60-The-magic-bean-script.pdf",
    pages: [],
    voiceover: "Oh no! Building a stand is so hard! Wood, nails, a roof... Maya is so tired! Welcome back to Cloud Town, high up in the sky! This is Episode 60. Meet the magic bean. Maya gives it her lemon. She plants it. Whoosh! Up grows a whole stand. Roof. Counter. Cups. And copy stands, ready to pop. Maya did not hammer one nail. She just makes lemonade. New flavor? Give the bean a strawberry. Whoosh! The stand is ready again. And Maya can still open the little door and change anything herself. You bring the lemon. The bean builds the rest. That is the magic bean. Now you know Elastic Beanstalk! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 61,
    title: "The night basket",
    tagline: "AWS Batch. Big jobs, done while you sleep.",
    video: "/61-The-night-basket.mp4?v=1",
    pdf: "/scripts/61-The-night-basket-script.pdf",
    scriptFile: "61-The-night-basket-script.pdf",
    pages: [],
    voiceover: "Oh no! A mountain of lemons! Maya can't squeeze them all! Welcome back to Cloud Town, high up in the sky! This is Episode 61. Meet the night basket. Maya puts the lemons inside. They wait in a line. Night comes. Maya goes to sleep. The moon on the lid glows. Out hop the little squeezers. One, two, ten! Squeeze, squeeze, squeeze! The big job gets done, lemon by lemon. The last lemon? Done! The squeezers hop back in. Nobody stays up for nothing. Morning. Pitchers everywhere! Maya did not squeeze one lemon. Big jobs, done while you sleep. That is the night basket. Now you know AWS Batch! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 62,
    title: "The toy shelf",
    tagline: "Amazon ECR. Same box, same taste, every stand.",
    video: "/62-The-toy-shelf.mp4?v=1",
    pdf: "/scripts/62-The-toy-shelf-script.pdf",
    scriptFile: "62-The-toy-shelf-script.pdf",
    pages: [],
    voiceover: "Oh no! Every cup tastes different! Too sour! Too sweet! Welcome back to Cloud Town, high up in the sky! This is Episode 62. Meet the toy shelf. Maya packs her best recipe in a lunchbox. Snap! Sealed tight. Onto the shelf. Every stand takes the same lunchbox. Sip. Yum! Sip. Yum! Every cup tastes the same. New recipe? A new lunchbox, with a green ribbon. The old one stays too, just in case. A muddy blob reaches for a box. Clack! The shelf closes. Only Cloud Town stands may take one. Same box, same taste, every stand. That is the toy shelf. Now you know Amazon ECR! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 63,
    title: "The town hall",
    tagline: "CloudFormation, Organizations, Control Tower, Systems Manager. Four helpers, one tidy town.",
    video: "/63-The-town-hall.mp4?v=1",
    pdf: "/scripts/63-The-town-hall-script.pdf",
    scriptFile: "63-The-town-hall-script.pdf",
    pages: [],
    voiceover: "Oh no! Cloud Town is growing too fast! Stands everywhere, and every one is different! Welcome back to Cloud Town, high up in the sky! This is Episode 63. Meet the town hall crew. First, the town stamp. Stamp! A whole street pops up, exactly right. Stamp! Another one, just the same. That is CloudFormation. Next, the family rope. It loops the houses into neighborhoods. One town, all together. That is Organizations. The lighthouse sets up each new neighborhood, safe from day one. That is Control Tower. And the magic toolbox fixes every stand at once. Tap, tap, done! That is Systems Manager. Four helpers, one tidy town. Now you know the town hall crew! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 64,
    title: "The town stamp",
    tagline: "AWS CloudFormation. Draw it once. Stamp it anywhere.",
    video: "/64-The-town-stamp.mp4?v=1",
    pdf: "/scripts/64-The-town-stamp-script.pdf",
    scriptFile: "64-The-town-stamp-script.pdf",
    pages: [],
    voiceover: "Oh no! Building a street by hand takes all day! And nothing matches! Welcome back to Cloud Town, high up in the sky! This is Episode 64. Meet the town stamp. Look underneath. A picture of the whole street. Stamp! The street pops up, exactly like the picture. Stamp again! Another street, just the same. Want flowers? Add them to the picture. Stamp! Now every stand has flowers. Done with a street? Lift and twist. Everything folds away. Nothing left behind. Draw it once. Stamp it anywhere. That is the town stamp. Now you know AWS CloudFormation! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 65,
    title: "The family rope",
    tagline: "AWS Organizations. One town, little neighborhoods, one rule for all.",
    video: "/65-The-family-rope.mp4?v=1",
    pdf: "/scripts/65-The-family-rope-script.pdf",
    scriptFile: "65-The-family-rope-script.pdf",
    pages: [],
    voiceover: "Oh no! Houses everywhere, floating apart! Who belongs where? Welcome back to Cloud Town, high up in the sky! This is Episode 65. Meet the family rope. It loops around every house. Pull! One town, all together. Little loops make neighborhoods. Blue roofs here. Green roofs there. Maya ties a red ribbon on the blue loop. Click, click, click! Every blue back door locks at once. One rule for the whole neighborhood. And one piggy bank pays for every house. A new house floats in. Loop! It joins the blue ones, and its door locks too. That is the family rope. Now you know AWS Organizations! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 66,
    title: "The lighthouse",
    tagline: "AWS Control Tower. Set up safe. Stay safe.",
    video: "/66-The-lighthouse.mp4?v=1",
    pdf: "/scripts/66-The-lighthouse-script.pdf",
    scriptFile: "66-The-lighthouse-script.pdf",
    pages: [],
    voiceover: "Oh no! A brand new neighborhood, and every gate is wide open! Welcome back to Cloud Town, high up in the sky! This is Episode 66. Meet the lighthouse. Its beam sweeps the new land. Fences! Lamps! Back doors lock. Safe from day one. The muddy blob bonks the fence. Nope! Need another neighborhood? Shine! The same safe setup, every single time. The lighthouse keeps watching. Green, green, green... red! One gate is open. Maya runs and closes it. Green again. Set up safe. Stay safe. That is the lighthouse. Now you know AWS Control Tower! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 67,
    title: "The magic toolbox",
    tagline: "AWS Systems Manager. One toolbox, every stand, all at once.",
    video: "/67-The-magic-toolbox.mp4?v=2",
    pdf: "/scripts/67-The-magic-toolbox-script.pdf",
    scriptFile: "67-The-magic-toolbox-script.pdf",
    pages: [],
    voiceover: "Oh no! Every stand is squeaking and wobbling! Welcome back to Cloud Town, high up in the sky! This is Episode 67. Meet the magic toolbox. Maya does not fix them one by one. She opens the toolbox. Whoosh! Sparkles fly to every stand at once. Squeak... gone! The toolbox can peek inside every stand. Pitcher? Cups? Lemons? Maya sees it all. This one has no cups. Tap! Cups appear. At night, while Maya sleeps, the toolbox works on its own. Polish, tighten, fix. Morning! Every stand shines. One toolbox, every stand, all at once. That is the magic toolbox. Now you know AWS Systems Manager! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 68,
    title: "The grown-up desk",
    tagline: "The Console, the CLI, and Trusted Advisor. Three helpers, one desk.",
    video: "/68-The-grown-up-desk.mp4?v=1",
    pdf: "/scripts/68-The-grown-up-desk-script.pdf",
    scriptFile: "68-The-grown-up-desk-script.pdf",
    pages: [],
    voiceover: "Oh no! So many stands, and Maya has to run to each one! Welcome back to Cloud Town, high up in the sky! This is Episode 68. Meet the grown-up desk. The button board shows every stand in little pictures. Press a button. Click! A stand opens. Easy to see, easy to press. That is the Console. The whisper tube is for quick helpers. Whisper once, and ten stands open. Whisper it again tomorrow. Same result. That is the CLI. And the wise turtle checks everything. Too many coins spent here! A gate left open there! It holds up little tips. That is Trusted Advisor. Three helpers, one desk. Now you know the grown-up desk! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 69,
    title: "The whisper tube",
    tagline: "AWS CLI. A few short words, and the work is done.",
    video: "/69-The-whisper-tube.mp4?v=1",
    pdf: "/scripts/69-The-whisper-tube-script.pdf",
    scriptFile: "69-The-whisper-tube-script.pdf",
    pages: [],
    voiceover: "Oh no! Twenty stands to open, and Maya presses twenty buttons, one by one! Her finger is so tired! Welcome back to Cloud Town, high up in the sky! This is Episode 69. Meet the whisper tube. The whisper tube has no buttons at all. Maya just whispers what she wants. Open the whole row! Whoosh! Twenty stands open at the same moment. And the tube remembers. Tomorrow morning, Maya whispers the same words. Same stands, same result, every single time. The tube can even reach the far-away towns, in one breath. Buttons are great for one stand. Whispers are great for many. That is the AWS CLI. You type a few short words, and AWS does all the work. Now you know the whisper tube! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 70,
    title: "The button board",
    tagline: "AWS Console. Look and press. Start here when you are new.",
    video: "/70-The-button-board.mp4?v=1",
    pdf: "/scripts/70-The-button-board-script.pdf",
    scriptFile: "70-The-button-board-script.pdf",
    pages: [],
    voiceover: "Oh no! One stand needs help, and Maya cannot see which one! The town is so big! Welcome back to Cloud Town, high up in the sky! This is Episode 70. Meet the button board. The board shows every stand in a little picture. Green means happy. Red means help. Maya taps the red one. Aha! No lemons! One button. Click! A basket slides in. The light turns green. Maya can see everything from one board. Cups, lemons, how long each stand has been open. No whispering, no magic words. Just look and press. That is the AWS Console. A screen with pictures and buttons for every helper. When you are new, you start here. Now you know the button board! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 71,
    title: "The wise turtle",
    tagline: "AWS Trusted Advisor. It points, kindly, at what you should fix.",
    video: "/71-The-wise-turtle.mp4?v=2",
    pdf: "/scripts/71-The-wise-turtle-script.pdf",
    scriptFile: "71-The-wise-turtle-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya's coins are leaking away, and she does not know why! Welcome back to Cloud Town, high up in the sky! This is Episode 71. Meet the wise turtle. The turtle walks around the whole town and checks everything. First card: the coin. That stand is lit all night with no customers. Turn it off, save your coins. Second card: the padlock. That back gate is wide open! Click. Safe. Third card: the heart. That stand has only one lamp. If it breaks, dark! Add a second one. The turtle does not fix things for you. It just points, kindly, at what you should fix. That is AWS Trusted Advisor. It checks your cost, your safety, and your backups, and gives you tips. Now you know the wise turtle! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 72,
    title: "The movers",
    tagline: "AWS migration. Five movers, one job: get everything up to the cloud.",
    video: "/72-The-movers.mp4?v=1",
    pdf: "/scripts/72-The-movers-script.pdf",
    scriptFile: "72-The-movers-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya's whole stand is still down on the ground, and Cloud Town is way up there! Welcome back to Cloud Town, high up in the sky! This is Episode 72. Meet the movers. The lift-cart slides under the whole stand and floats it up in one piece. The pour-pitcher pours the old notebook into a new one, page by page, while Maya keeps writing. The bucket-chain passes lemons up, one by one, fast. The snow-box carries a whole mountain of lemons at once. And the mail-chute lets friends drop letters the old way, straight into the cloud. Five movers, one job: get everything up to the cloud, safely. That is AWS migration. Now you know the movers! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 73,
    title: "The lift-cart",
    tagline: "AWS Application Migration Service. Lift the whole server as it is, while it keeps running.",
    video: "/73-The-lift-cart.mp4?v=2",
    pdf: "/scripts/73-The-lift-cart-script.pdf",
    scriptFile: "73-The-lift-cart-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya's old stand is too heavy to carry up to the clouds! Welcome back to Cloud Town, high up in the sky! This is Episode 73. Meet the lift-cart. It slides under the whole stand, just as it is. Friends keep buying cups the whole time. Then the balloons puff up. The stand lifts off, counter, cups, pitcher, everything, in one piece. Up through the clouds. Not one drop spilled. On the cloud, it lands in its new spot. Same stand, same cups, same pitcher, now up in Cloud Town. Nothing to rebuild, nothing to repack. That is AWS Application Migration Service, MGN. It lifts a whole server to the cloud as it is, while it keeps running. Now you know the lift-cart! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 74,
    title: "The pour-pitcher",
    tagline: "AWS Database Migration Service. Copy the pages while the old notebook keeps working.",
    video: "/74-The-pour-pitcher.mp4?v=1",
    pdf: "/scripts/74-The-pour-pitcher-script.pdf",
    scriptFile: "74-The-pour-pitcher-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya's notebook has every recipe, and she cannot carry it up without losing pages! Welcome back to Cloud Town, high up in the sky! This is Episode 74. Meet the pour-pitcher. It dips its spout into the old notebook and pours the pages up, one by one. And Maya keeps writing the whole time. The new drawing flows up too. Up on the cloud, the pages land in a new notebook, in the same order. Not one page lost. Not one minute closed. That is AWS Database Migration Service, DMS. It copies a database to the cloud while the old one keeps working. Now you know the pour-pitcher! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 75,
    title: "The bucket-chain",
    tagline: "AWS DataSync. Move the big pile up, fast, and check every one.",
    video: "/75-The-bucket-chain.mp4?v=1",
    pdf: "/scripts/75-The-bucket-chain-script.pdf",
    scriptFile: "75-The-bucket-chain-script.pdf",
    pages: [],
    voiceover: "Oh no! A whole crate of lemons, and Maya can carry only two at a time! Welcome back to Cloud Town, high up in the sky! This is Episode 75. Meet the bucket-chain. One rope, many buckets, from the ground all the way up to the cloud. Scoop, lift, tip, back down. Again and again, fast and steady. One bucket is chipped? Swap it. The chain never stops. Up top, every lemon lands in its cubby box. Same lemons, same order, nothing lost. That is AWS DataSync. It moves big piles of files to the cloud, fast, and checks every one. Now you know the bucket-chain! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 76,
    title: "The snow-box",
    tagline: "AWS Snow Family. Big tough boxes that carry huge piles to the cloud by truck.",
    video: "/76-The-snow-box.mp4?v=3",
    pdf: "/scripts/76-The-snow-box-script.pdf",
    scriptFile: "76-The-snow-box-script.pdf",
    pages: [],
    voiceover: "Oh no! A mountain of lemons, and the bucket-chain lifts one lemon at a time! That would take all year! Welcome back to Cloud Town, high up in the sky! This is Episode 76. Meet the snow-box. It is big, padded, and very tough. Maya fills it with the whole mountain. Click, the lid shuts. A truck drives it up the ramp to the cloud. Up top, the lid opens, and the whole mountain lands at once. When the pile is too big for the rope, you ship the box. That is the AWS Snow Family. Big tough boxes that carry huge piles of data to the cloud by truck. Now you know the snow-box! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 77,
    title: "The mail-chute",
    tagline: "AWS Transfer Family. Friends send files the old way, and they land in the cloud.",
    video: "/77-The-mail-chute.mp4?v=1",
    pdf: "/scripts/77-The-mail-chute-script.pdf",
    scriptFile: "77-The-mail-chute-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya moved to the cloud, but her friends still send letters to the old mailbox on the ground! Welcome back to Cloud Town, high up in the sky! This is Episode 77. Meet the mail-chute. Its pipe reaches down from the cloud, and its flap sits right where the old mailbox was. Same flap, same way. Friends drop a letter in, just like always. Whoosh! It lands in the cloud cubby. Nobody has to learn anything new. That is the AWS Transfer Family. Friends send files the old way, and they land in the cloud. Now you know the mail-chute! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 78,
    title: "The library",
    tagline: "AWS analytics. From a mountain of notes to one picture.",
    video: "/78-The-library.mp4?v=1",
    pdf: "/scripts/78-The-library-script.pdf",
    scriptFile: "78-The-library-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya has a mountain of notes, and no idea what they say! Welcome back to Cloud Town, high up in the sky! This is Episode 78. Meet the library. The sticky-pot cleans the cards and stacks them neat. The river chute brings new cards as they come. The reading lamp finds the answer in a pile, no sorting needed. The pointer bird darts to the one card you want. The ant crew moves a whole mountain of cards in minutes. The tall tower keeps millions in tiny drawers. And the easel paints the answer as a picture. That is AWS analytics: Glue, Kinesis, Athena, OpenSearch, EMR, Redshift and QuickSight. Now you know the library! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 79,
    title: "The reading lamp",
    tagline: "Amazon Athena. Ask the files where they sit. Pay only for the question.",
    video: "/79-The-reading-lamp.mp4?v=1",
    pdf: "/scripts/79-The-reading-lamp-script.pdf",
    scriptFile: "79-The-reading-lamp-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya wants to know how many cups she sold on sunny days, and the cards are one big mess! Welcome back to Cloud Town, high up in the sky! This is Episode 79. Meet the reading lamp. Maya asks one question: sunny days? The lamp shines on the pile. Every sunny card glows and floats up. Count them. Done. The pile never moved. No sorting, no new shelf, no copying. Ask, shine, answer. Another pile? Shine there too. That is Amazon Athena. It asks questions straight to your files where they sit, and you pay only for the question. Now you know the reading lamp! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 80,
    title: "The shelf-tower",
    tagline: "Amazon Redshift. A giant warehouse, built to answer big questions fast.",
    video: "/80-The-shelf-tower.mp4?v=1",
    pdf: "/scripts/80-The-shelf-tower-script.pdf",
    scriptFile: "80-The-shelf-tower-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya has too many cards for her little shelf, and it is about to burst! Welcome back to Cloud Town, high up in the sky! This is Episode 80. Meet the shelf-tower. It is tall, very tall, with hundreds of tiny drawers. Every card goes in its own drawer, cups with cups, lemons with lemons. Ask a big question: cups sold at night? Hundreds of drawers open at once. The answer stacks up in a second. Millions of cards, one quick answer. The little shelf is for a few cards. The tower is for a whole town of cards. That is Amazon Redshift. A giant warehouse for your data, built to answer big questions fast. Now you know the shelf-tower! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 81,
    title: "The sticky-pot",
    tagline: "AWS Glue. Clean the messy cards first, then ask.",
    video: "/81-The-sticky-pot.mp4?v=2",
    pdf: "/scripts/81-The-sticky-pot-script.pdf",
    scriptFile: "81-The-sticky-pot-script.pdf",
    pages: [],
    voiceover: "Oh no! The cards are torn, folded and upside down, and the lamp cannot read them! Welcome back to Cloud Town, high up in the sky! This is Episode 81. Meet the sticky-pot. Its brush gets to work. Flatten the folded ones. Flip the upside-down ones. Stick the torn ones back together. Trim them all to one size. Then one neat stack, all facing up. Now the lamp shines, and the answer floats up at once. Clean first, then ask. That is AWS Glue. It cleans and tidies messy data so the other helpers can use it. Now you know the sticky-pot! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 82,
    title: "The river chute",
    tagline: "Amazon Kinesis. A live stream of notes, the moment they are made.",
    video: "/82-The-river-chute.mp4?v=2",
    pdf: "/scripts/82-The-river-chute-script.pdf",
    scriptFile: "82-The-river-chute-script.pdf",
    pages: [],
    voiceover: "Oh no! Cups are selling so fast, Maya cannot catch the cards as they come! Welcome back to Cloud Town, high up in the sky! This is Episode 82. Meet the river chute. Every new card floats down, one after another, in order. The lamp reads them on the way. Count, count, count, as they go by. More cups? The river gets wider. Two lanes, three lanes, nothing bumps. At the end, every card lands in the basket, still in order. The notes flow like a river, live, as things happen. That is Amazon Kinesis. It carries a live stream of data the moment it is made. Now you know the river chute! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 83,
    title: "The pointer bird",
    tagline: "Amazon OpenSearch. Find the right card, even from a smudge.",
    video: "/83-The-pointer-bird.mp4?v=1",
    pdf: "/scripts/83-The-pointer-bird-script.pdf",
    scriptFile: "83-The-pointer-bird-script.pdf",
    pages: [],
    voiceover: "Oh no! One heart card, somewhere in a thousand cards, and Maya is flipping one by one! Welcome back to Cloud Town, high up in the sky! This is Episode 83. Meet the pointer bird. Show it what you want. Zip! It darts into the pile and pulls out the one card. Two things at once? Zip, zip, zip, three boxes. A smudged drawing? It still finds the closest match. It does not read the whole pile. It already knows where everything is. That is Amazon OpenSearch. It finds the right thing in a huge pile, fast, even when you are not sure of the exact word. Now you know the pointer bird! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 84,
    title: "The ant crew",
    tagline: "Amazon EMR. A big crew that chews through a mountain, then goes away.",
    video: "/84-The-ant-crew.mp4?v=1",
    pdf: "/scripts/84-The-ant-crew-script.pdf",
    scriptFile: "84-The-ant-crew-script.pdf",
    pages: [],
    voiceover: "Oh no! A mountain of cards, and Maya can sort one card at a time! The sun is going down! Welcome back to Cloud Town, high up in the sky! This is Episode 84. Meet the ant crew. Hundreds of tiny ants, each one carries one card. Cups to the red mat, lemons to the yellow, suns to the blue. All at the same time. The mountain melts. Need it faster? Clap, and more ants come. Done? They march home. You only pay while they work. That is Amazon EMR. A big crew of helpers that chews through a mountain of data together, then goes away. Now you know the ant crew! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 85,
    title: "The picture easel",
    tagline: "Amazon QuickSight. Turn the stacks into a picture you see in one look.",
    video: "/85-The-picture-easel.mp4?v=1",
    pdf: "/scripts/85-The-picture-easel-script.pdf",
    scriptFile: "85-The-picture-easel-script.pdf",
    pages: [],
    voiceover: "Oh no! Three stacks of cards, and Maya cannot tell which is biggest just by looking! Welcome back to Cloud Town, high up in the sky! This is Episode 85. Meet the picture easel. It paints the answer. Three bars: tall, medium, short. Now you see it in one look. A circle cut into slices: which part is biggest? A wavy line going up: are we growing? Yes! Add a new card, and the picture grows by itself. No counting, no squinting. Just look. That is Amazon QuickSight. It turns your data into simple pictures you understand in a second. Now you know the picture easel! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 86,
    title: "The talking friends",
    tagline: "AWS AI. Nine friends that see, hear, write, and learn.",
    video: "/86-The-talking-friends.mp4?v=1",
    pdf: "/scripts/86-The-talking-friends-script.pdf",
    scriptFile: "86-The-talking-friends-script.pdf",
    pages: [],
    voiceover: "Oh no! Maya shows a picture and talks, and nobody in the room understands her! Welcome back to Cloud Town, high up in the sky! This is Episode 86. Meet the talking friends. The eye looks at a picture and says what it sees. The ear listens and knows if you are happy or sad. The bell reads cards out loud. The quill writes down what it hears. The bridge turns your words into another language. The window pulls drawings off a paper. The parrot chats back. The owl finds the one card you need. And the little robot? It learns by watching, and gets better every day. That is AWS AI: Rekognition, Comprehend, Polly, Transcribe, Translate, Textract, Lex, Kendra and SageMaker. Now you know the talking friends! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 87,
    title: "The learning robot",
    tagline: "Amazon SageMaker. Show it examples, and it learns the job.",
    video: "/87-The-learning-robot.mp4?v=1",
    pdf: "/scripts/87-The-learning-robot-script.pdf",
    scriptFile: "87-The-learning-robot-script.pdf",
    pages: [],
    voiceover: "Oh no! A mountain of fruit cards, and Maya has to sort every single one by hand! Welcome back to Cloud Town, high up in the sky! This is Episode 87. Meet the learning robot. Maya shows it a lemon. Yellow bowl. A lime. Green bowl. The robot watches. It tries one. Oops, wrong bowl. Maya fixes it, and the robot remembers. Try again. Right! And again. Right! The more examples it sees, the smarter it gets. Now it sorts all by itself. A brand new card? It thinks, and still gets it right. That is Amazon SageMaker. You show it examples, it learns the pattern, and then it does the job for you. Now you know the learning robot! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 88,
    title: "The seeing eye",
    tagline: "Amazon Rekognition. It looks at the pictures and tells you what is in them.",
    video: "/88-The-seeing-eye.mp4?v=2",
    pdf: "/scripts/88-The-seeing-eye-script.pdf",
    scriptFile: "88-The-seeing-eye-script.pdf",
    pages: [],
    voiceover: "Oh no! A giant pile of photos, and Maya has to look at every single one to sort them! Welcome back to Cloud Town, high up in the sky! This is Episode 88. Meet the seeing eye. Show it a photo. It looks, and tells you what is inside. A lemon! A dog! A boat! It never gets tired. Blurry photo? It looks closer, and still knows. Three things in one photo? It spots all three. Maya just holds them up, and the eye does the looking. That is Amazon Rekognition. It looks at pictures and videos, and tells you what is in them. Now you know the seeing eye! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 89,
    title: "The listening ear",
    tagline: "Amazon Comprehend. It hears the feeling and the meaning.",
    video: "/89-The-listening-ear.mp4?v=1",
    pdf: "/scripts/89-The-listening-ear-script.pdf",
    scriptFile: "89-The-listening-ear-script.pdf",
    pages: [],
    voiceover: "Oh no! A heap of notes from the stands, and Maya cannot tell which ones are happy and which ones are sad! Welcome back to Cloud Town, high up in the sky! This is Episode 89. Meet the listening ear. Tap a note. The ear listens. Happy! Into the sunny jar. Tap another. Sad. Into the cloudy jar. It never gets mixed up. And it hears more. This note is happy, and it is about lemons. That one is about cups. A whole stack goes by, and the ear sorts every feeling and every topic. That is Amazon Comprehend. It reads words and understands the feeling and the meaning behind them. Now you know the listening ear! See you next time in Cloud Town, high up in the sky!",
  },
];
