export type EpisodeScript = {
  n: number;
  title: string;
  tagline: string;
  video: string;
  pdf: string;
  scriptFile: string;
  pages: string[];
  voiceover: string;
};

export const EPISODE_SCRIPTS: EpisodeScript[] = [
  {
    n: 0,
    title: "What is the cloud?",
    tagline: "Not weather. A town of helpers in the sky.",
    video: "/00-What-is-the-cloud.mp4?v=native9x16",
    pdf: "/scripts/00-What-is-the-cloud-script.pdf",
    scriptFile: "00-What-is-the-cloud-script.pdf",
    pages: ["/script-pages/00-What-is-the-cloud-script-p1.jpg"],
    voiceover: "Welcome! This is Maya. She is at home, on the ground, playing a game on her tablet. But wait. Where does the game live? Not in the tablet. Look up! We fly through the real clouds. A town is floating in the sky. Cream houses. Teal lamps. The cloud is not weather. It is a town of helpers, high in the sky, that keeps your stuff and runs your games. That chest keeps things. That computer runs things. That little spark pops in for one job. Maya taps play. A tiny light flies from her tablet, up to the town, and back. The game loads! The cloud is a town of helpers in the sky. Now you know the cloud! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 1,
    title: "The helpers",
    tagline: "Sammy stores. Eddie runs. Lulu pops in.",
    video: "/01-The-helpers.mp4?v=9x16",
    pdf: "/scripts/01-The-helpers-script.pdf",
    scriptFile: "01-The-helpers-script.pdf",
    pages: ['/script-pages/01-The-helpers-script-p1.jpg', '/script-pages/01-The-helpers-script-p2.jpg'],
    voiceover: "Welcome to Cloud Town, high up in the sky! Meet Sammy the Super Storage Box. Sammy is S3. He keeps photos, toys, and files safe forever. Here's Eddie. Eddie is EC2, a computer who never sleeps. He runs websites and games all day long. And this is Lulu. Lulu is Lambda. She pops in, does one job super fast, then poofs away. Together they make the cloud work. Now you know AWS!",
  },
  {
    n: 2,
    title: "Sammy\u2019s closet",
    tagline: "Buckets, shelves, and the whole freezer family.",
    video: "/02-Sammys-closet.mp4?v=9x16",
    pdf: "/scripts/02-Sammy-s-closet-script.pdf",
    scriptFile: "02-Sammy-s-closet-script.pdf",
    pages: ['/script-pages/02-Sammy-s-closet-script-p1.jpg', '/script-pages/02-Sammy-s-closet-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 2. Meet Sammy the Super Storage Box. Sammy is S3. His closet is a bucket. Each drawing is an object. He never fills up. The everyday shelf is S3 Standard. You can open it any time. The dusty shelf is Infrequent Access. It is cheaper if you do not peek every day. One Zone-IA lives in just one yard. Intelligent-Tiering is a magic closet. It moves drawings to cheaper shelves by itself. Glacier Instant is a chilly drawer you can open right now. Glacier Flexible Retrieval waits a little. Glacier Deep Archive sleeps for years. Now you know Sammy's closet!",
  },
  {
    n: 3,
    title: "Copies and locks",
    tagline: "Versioning, copies across towns, and doors that stay shut.",
    video: "/03-Copies-and-locks.mp4?v=9x16",
    pdf: "/scripts/03-Copies-and-locks-script.pdf",
    scriptFile: "03-Copies-and-locks-script.pdf",
    pages: ['/script-pages/03-Copies-and-locks-script-p1.jpg', '/script-pages/03-Copies-and-locks-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 3. Sammy keeps old drawings too. Versioning keeps the old drawing when you paint a new one. A lifecycle rule tucks old drawings into the freezer by itself. Sammy copies treasures into many buildings. Eleven nines means they almost never vanish. Cross-Region Replication sends a copy to another Cloud Town. Encryption is a padlock on the closet. Block Public Access keeps strangers out. Object Lock says this drawing may not be erased. Old drawings stay. Copies fly. Locks stay shut. Now you know copies and locks!",
  },
  {
    n: 4,
    title: "The neighborhood",
    tagline: "A fence, a front street, a backyard, and a tunnel home.",
    video: "/04-The-neighborhood.mp4?v=ana",
    pdf: "/scripts/04-The-neighborhood-script.pdf",
    scriptFile: "04-The-neighborhood-script.pdf",
    pages: ['/script-pages/04-The-neighborhood-script-p1.jpg', '/script-pages/04-The-neighborhood-script-p2.jpg', '/script-pages/04-The-neighborhood-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Meet Vivi the fence. A VPC is our own private neighborhood. Front street is public. The backyard is private. Iggie is the Internet Gateway, the big front gate! Albie the doorman greets visitors on the public street. Eddie the computer and Dot the vault hide in the backyard. Nat the mail window lets Eddie go out, but strangers cannot come in. That's egress! A sky bridge links another town. A secret tunnel reaches a house on the ground. Now you know the neighborhood! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 5,
    title: "The other boxes",
    tagline: "A backpack, a fridge, fancy cupboards, a door at home, and a spare.",
    video: "/05-The-other-boxes.mp4?v=ana",
    pdf: "/scripts/05-The-other-boxes-script.pdf",
    scriptFile: "05-The-other-boxes-script.pdf",
    pages: ['/script-pages/05-The-other-boxes-script-p1.jpg', '/script-pages/05-The-other-boxes-script-p2.jpg', '/script-pages/05-The-other-boxes-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 5. Sammy the Super Storage Box has a surprise. He has more than one closet! First, meet Eddie's backpack disk. That is EBS. It belongs to one Eddie and travels with him. Next, the shared fridge. That is EFS. Many Eddies can open it at the same time. These fancy cupboards are FSx. Way in the back is the deep freezer. That is S3 Glacier. Old drawings sleep here. It is cheap, and slow to open. A little door at home is Storage Gateway. And this is Backup, the spare-copy machine. Now you know Sammy's closets! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 6,
    title: "The key keepers",
    tagline: "Name tags, school badges, guest stickers, and a shared swing.",
    video: "/06-The-key-keepers.mp4?v=9x16",
    pdf: "/scripts/06-The-key-keepers-script.pdf",
    scriptFile: "06-The-key-keepers-script.pdf",
    pages: ['/script-pages/06-The-key-keepers-script-p1.jpg', '/script-pages/06-The-key-keepers-script-p2.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 6. A town with no keys is not safe. A town with one shared key is not safe either. Meet the key ring. That is IAM. Users have name tags. Groups are a whole class. A role is a badge you borrow for one job. A policy is the list of may and may-not. Identity Center is one school badge that opens many classrooms. Cognito is a guest sticker for friends who do not live here. Directory Service brings the old class list into the sky. RAM shares a swing, not the house key. Now you know the key keepers!",
  },
  {
    n: 7,
    title: "The key ring",
    tagline: "User, role, policy, SCP, and STS.",
    video: "/07-The-key-ring.mp4?v=9x16",
    pdf: "/scripts/07-The-key-ring-script.pdf",
    scriptFile: "07-The-key-ring-script.pdf",
    pages: ['/script-pages/07-The-key-ring-script-p1.jpg', '/script-pages/07-The-key-ring-script-p2.jpg', '/script-pages/07-The-key-ring-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 7. Today we open the key ring all the way. That is IAM. A user is a kid with a name tag. That kid lives in town. A role is a badge you borrow for one job, then you give it back. A policy is the list of may and may-not on the door. An SCP is the principal's rule. No classroom may break it, even if a teacher says yes. STS is a visitor pass that peels off at sunset. You borrow keys for a little while, then they vanish. Name tag. Borrowed badge. Door list. Principal's rule. Sunset pass. Now you know IAM!",
  },
  {
    n: 8,
    title: "The school badge",
    tagline: "One badge, many classrooms \u2014 not a name tag, not a guest sticker.",
    video: "/08-The-school-badge.mp4?v=9x16",
    pdf: "/scripts/08-The-school-badge-script.pdf",
    scriptFile: "08-The-school-badge-script.pdf",
    pages: ['/script-pages/08-The-school-badge-script-p1.jpg', '/script-pages/08-The-school-badge-script-p2.jpg', '/script-pages/08-The-school-badge-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 8. The school badge is IAM Identity Center. One badge opens many classrooms. The office picks the class list. That is the identity source. Cloud Town's own list, the old class list, or another school. A permission set is which rooms the badge opens. Each classroom is an AWS account. You sign in once. This is not an IAM name tag. A name tag only works in one house. This is not a Cognito guest sticker. Guest stickers are for lemonade. The school badge is for the whole school. Now you know Identity Center!",
  },
  {
    n: 9,
    title: "The guest sticker",
    tagline: "User pools, identity pools, lemonade guests \u2014 not town workers.",
    video: "/09-The-guest-sticker.mp4?v=9x16",
    pdf: "/scripts/09-The-guest-sticker-script.pdf",
    scriptFile: "09-The-guest-sticker-script.pdf",
    pages: ['/script-pages/09-The-guest-sticker-script-p1.jpg', '/script-pages/09-The-guest-sticker-script-p2.jpg', '/script-pages/09-The-guest-sticker-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 9. Meet the guest sticker. That is Amazon Cognito. It is for friends who buy lemonade, not for kids who work in town. A user pool is the lemonade club list. Guests sign up and get a sticker. An identity pool is a tray of sunset passes. A guest can peek at one drawing, then the pass peels off. That uses STS. You can sign in at the lemonade window. Or use a badge from another playground. This is not IAM. A name tag is for workers. This is not Identity Center. A school badge is for the whole school. Cognito is for the lemonade stand. Now you know Cognito!",
  },
  {
    n: 10,
    title: "The vaults",
    tagline: "Pick the vault that matches the treasure.",
    video: "/10-The-vaults.mp4?v=9x16",
    pdf: "/scripts/10-The-vaults-script.pdf",
    scriptFile: "10-The-vaults-script.pdf",
    pages: ['/script-pages/10-The-vaults-script-p1.jpg', '/script-pages/10-The-vaults-script-p2.jpg', '/script-pages/10-The-vaults-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 10. Meet Dot. She is a vault. But Dot is not only one vault. RDS is a tidy notebook. AWS turns the pages. Aurora is the super notebook. Extra copies. Extra fast. Aurora Serverless wakes when you write, then naps. DynamoDB is labeled cubbies. Grab by name. Super fast. ElastiCache is the snack already unwrapped. DocumentDB keeps JSON stories. Neptune is a family tree. Keyspaces are wide cubbies. Pick the vault that matches the treasure. Now you know the vaults!",
  },
  {
    n: 11,
    title: "The tidy notebook",
    tagline: "AWS turns the pages.",
    video: "/11-The-tidy-notebook.mp4?v=9x16",
    pdf: "/scripts/11-The-tidy-notebook-script.pdf",
    scriptFile: "11-The-tidy-notebook-script.pdf",
    pages: ['/script-pages/11-The-tidy-notebook-script-p1.jpg', '/script-pages/11-The-tidy-notebook-script-p2.jpg', '/script-pages/11-The-tidy-notebook-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 11. RDS is Amazon RDS. A tidy notebook with rows and columns. AWS turns the pages. You pick the brand. MySQL. PostgreSQL. And more. Eddie asks Dot in the backyard. Visitors never meet her. That is a private street. If one notebook gets sleepy, a spare waits in the other yard. That is Multi-AZ. A reading copy keeps the line short. That is a replica. At night, AWS photocopies the pages. Those are backups. AWS does the grown-up jobs. Now you know RDS!",
  },
  {
    n: 12,
    title: "The super notebook",
    tagline: "Extra copies. Extra fast. Then it naps.",
    video: "/12-The-super-notebook.mp4?v=9x16",
    pdf: "/scripts/12-The-super-notebook-script.pdf",
    scriptFile: "12-The-super-notebook-script.pdf",
    pages: ['/script-pages/12-The-super-notebook-script-p1.jpg', '/script-pages/12-The-super-notebook-script-p2.jpg', '/script-pages/12-The-super-notebook-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 12. RDS is a tidy notebook. Aurora is the super notebook. Extra copies. Extra fast. It still speaks MySQL. It still speaks PostgreSQL. All the notebooks share one big pile of pages. Write once. Everyone can read. Extra copies help the line stay short. Those are replicas. They share the same pile. When nobody writes, Aurora Serverless takes a nap. When Eddie writes, it wakes up. AWS grows the pages. Now you know Aurora!",
  },
  {
    n: 13,
    title: "The nap",
    tagline: "Sleeps when empty. Grows for a crowd. You pay for a sip.",
    video: "/13-The-nap.mp4?v=9x16",
    pdf: "/scripts/13-The-nap-script.pdf",
    scriptFile: "13-The-nap-script.pdf",
    pages: ['/script-pages/13-The-nap-script-p1.jpg', '/script-pages/13-The-nap-script-p2.jpg', '/script-pages/13-The-nap-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 13. Aurora can stay wide awake. That is provisioned. Or Aurora can nap. That is Aurora Serverless. When the lemonade stand is empty, the notebook sleeps. You do not pay for a whole pitcher. You pay for a sip. When a crowd comes, it wakes and grows. ACU is how wide the pages get. Lulu pops in for one job, then she is gone. This notebook stays. It just takes a nap. Still MySQL. Still PostgreSQL. Same pile of pages. Now you know Aurora Serverless!",
  },
  {
    n: 14,
    title: "The labeled cubbies",
    tagline: "Grab by name. Super fast. No rows to turn.",
    video: "/14-The-labeled-cubbies.mp4?v=9x16",
    pdf: "/scripts/14-The-labeled-cubbies-script.pdf",
    scriptFile: "14-The-labeled-cubbies-script.pdf",
    pages: ['/script-pages/14-The-labeled-cubbies-script-p1.jpg', '/script-pages/14-The-labeled-cubbies-script-p2.jpg', '/script-pages/14-The-labeled-cubbies-script-p3.jpg'],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 14. RDS is a tidy notebook. Aurora is a super notebook. You turn pages. DynamoDB is labeled cubbies. Grab by name. Super fast. No rows to turn. Eddie already knows the name. He does not hunt through a notebook. The name on the cubby is the partition key. The order inside is the sort key. When a cubby changes, a whisper goes out. That is a stream. Extra labels help you find things another way. Those are GSIs. Always on. No nap needed. Now you know DynamoDB!",
  },
  {
    n: 15,
    title: "The cubby extras",
    tagline: "DAX, twin towns, paying for grabs, now vs in a moment.",
    video: "/15-The-cubby-extras.mp4?v=9x16",
    pdf: "/scripts/15-The-cubby-extras-script.pdf",
    scriptFile: "15-The-cubby-extras-script.pdf",
    pages: ["/script-pages/15-The-cubby-extras-script-p1.jpg", "/script-pages/15-The-cubby-extras-script-p2.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 15. DynamoDB is labeled cubbies. Here are the extras. DAX is a snack shelf only for cubbies. Repeats come instantly. You do not open the cubby every time. Global tables are the same cubbies in another town. Write here. It shows up there. Friends far away see the same toys. On-demand means you pay per grab. One coin for one lemon. Provisioned means you save a line for busy days. A strong read is now. An eventual read is in a moment. Now you know the cubby extras! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 16,
    title: "The unwrapped snack",
    tagline: "ElastiCache. Redis or Memcached. Not the vault.",
    video: "/16-The-unwrapped-snack.mp4?v=9x16",
    pdf: "/scripts/16-The-unwrapped-snack-script.pdf",
    scriptFile: "16-The-unwrapped-snack-script.pdf",
    pages: ["/script-pages/16-The-unwrapped-snack-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 16. Repeats should not knock on the vault every time. Eddie can grab a snack instead. ElastiCache is the unwrapped snack. Redis or Memcached. A snack already open. Redis can remember a list. Memcached is a simple tray. If the snack tray tips, the real notebook still has the recipe. Dot is safe. The snack is not the vault. DAX is a snack only for cubbies. ElastiCache can sit in front of notebooks too. Hot reads come instantly. Now you know the unwrapped snack! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 17,
    title: "The story vault",
    tagline: "DocumentDB. A whole tale as one pile of pages.",
    video: "/17-The-story-vault.mp4?v=9x16",
    pdf: "/scripts/17-The-story-vault-script.pdf",
    scriptFile: "17-The-story-vault-script.pdf",
    pages: ["/script-pages/17-The-story-vault-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 17. Dot has a tidy notebook. Rows and columns. The cubbies grab by name. The story vault is different. DocumentDB keeps a whole tale as one pile of pages. Like a storybook. Name, pictures, and notes stay together. You do not split the tale into rows. You do not need the same boxes on every page. It talks like MongoDB. Eddie can read the whole story at once. If a page is missing, the tale still makes sense. Now you know the story vault! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 18,
    title: "The family tree",
    tagline: "Neptune. Who is related to who. That is a graph.",
    video: "/18-The-family-tree.mp4?v=9x16",
    pdf: "/scripts/18-The-family-tree-script.pdf",
    scriptFile: "18-The-family-tree-script.pdf",
    pages: ["/script-pages/18-The-family-tree-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 18. Dot has rows. Cubbies grab by name. The story vault is a pile of pages. Neptune is the family tree. It does not store a list. It stores who is related to who. Maya is friends with Eddie. Eddie is friends with Lulu. The tree shows the whole web. You ask, who knows who? Super fast. A list would take forever. The tree already knows the path. Friends of friends light up too. That is a graph. Now you know the family tree! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 19,
    title: "The wide cubbies",
    tagline: "Keyspaces. Cassandra-style. One name, a long row of slots.",
    video: "/19-The-wide-cubbies.mp4?v=9x16",
    pdf: "/scripts/19-The-wide-cubbies-script.pdf",
    scriptFile: "19-The-wide-cubbies-script.pdf",
    pages: ["/script-pages/19-The-wide-cubbies-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! This is Episode 19. Dynamo cubbies grab by name. One toy per cubby. Keyspaces is wide cubbies. One name, then a long row of slots. Like Cassandra. A whole week of drawings stay in one wide cubby. You can peek a slice. You do not hunt the whole town. Eddie talks Cassandra talk. AWS keeps the house. You do not build it yourself. Many towns can share the wide cubbies. Super wide. Super fast. Now you know the wide cubbies! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 20,
    title: "The toy boxes",
    tagline: "Boxy, Kira, and Fay. Many Eddies in boxes.",
    video: "/20-The-toy-boxes.mp4?v=story",
    pdf: "/scripts/20-The-toy-boxes-script.pdf",
    scriptFile: "20-The-toy-boxes-script.pdf",
    pages: ["/script-pages/20-The-toy-boxes-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya's class all tap play at once. Twenty games! One Eddie cannot do it. He wobbles. Toys drop. Boxy opens! Little Eddies pop out and run the jobs. Boxy is ECS. A toy box that runs many Eddies. Tweet! Kira blows her whistle. Five Boxys line up in a row. Kira is EKS. The captain of the toy boxes. Whoosh! Fay flies a box up to a house. No Eddie under it! Fay is Fargate. She flies. No Eddie has to hold the box. The games load. All twenty! Maya cheers. Now you know the toy boxes! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 21,
    title: "Boxy",
    tagline: "ECS. One box. Many jobs. If a little Eddie stops, Boxy pops a new one in.",
    video: "/21-Boxy.mp4?v=story",
    pdf: "/scripts/21-Boxy-script.pdf",
    scriptFile: "21-Boxy-script.pdf",
    pages: ["/script-pages/21-Boxy-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has many tiny jobs. Wrap this. Carry that. Tap this. One Eddie cannot hold them all. Into Boxy they go! One box. Many little Eddies pop out and run every job. That is ECS. A toy box that runs many Eddies. Oh no! One little Eddie inside stops. That one job goes dark. Maya's toy freezes. Boxy sees it. Pop! A new little Eddie jumps in. The job lights up again. The box keeps the jobs running. Now you know Boxy! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 22,
    title: "Kira",
    tagline: "EKS. The captain of the toy boxes. The whole row works in step.",
    video: "/22-Kira.mp4?v=story",
    pdf: "/scripts/22-Kira-script.pdf",
    scriptFile: "22-Kira-script.pdf",
    pages: ["/script-pages/22-Kira-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has five Boxys. Each one does its own thing. Toys everywhere! Nothing lines up. Kira is the captain of the toy boxes. Tweet! She blows her whistle. The boxes line up. This box wraps. That box carries. That box taps. Oh no! One box tips over. Kira puts a new box in its place. The line gets long. Kira adds one more. Now the whole row works in step. That is EKS. Now you know Kira! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 23,
    title: "Fay",
    tagline: "Fargate. She flies the box. No Eddie underneath.",
    video: "/23-Fay.mp4?v=story",
    pdf: "/scripts/23-Fay-script.pdf",
    scriptFile: "23-Fay-script.pdf",
    pages: ["/script-pages/23-Fay-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Maya has a box of jobs. Wrap this. Carry that. Tap this. But every Eddie in town is busy. Nobody can carry the box. Look: Boxy sits on Eddie's head. Boxy needs an Eddie. Whoosh! Fay flies in. She is a flying box. She carries the jobs herself. No Eddie underneath! The jobs run while she flies. When the jobs are done, Fay lands and rests. Eddie can go play. Nobody pays for an Eddie that sits idle. That is Fargate. Now you know Fay! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 24,
    title: "The front door",
    tagline: "Mapi points. Zip copies at the edge. Boost is one fast door.",
    video: "/24-The-front-door.mp4?v=story",
    pdf: "/scripts/24-The-front-door-script.pdf",
    scriptFile: "24-The-front-door-script.pdf",
    pages: ["/script-pages/24-The-front-door-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Remy is a visitor from far away. He wants to see Maya's drawing. He gets lost on the path. Then he arrives so slow. Oh no! Mapi is the town map. She is a signpost. She points him to the right house. Zip is the fast road. A copy of the drawing waits at the edge of town. Remy does not walk all the way in. He gets it right there. Boost is the rocket path. One front door. Always the fastest road, no matter where he starts. Remy smiles at the drawing. Now you know the front door! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 25,
    title: "Mapi",
    tagline: "Route 53. She points by name, not by color. That is failover.",
    video: "/25-Mapi.mp4?v=mapi2",
    pdf: "/scripts/25-Mapi-script.pdf",
    scriptFile: "25-Mapi-script.pdf",
    pages: ["/script-pages/25-Mapi-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Eddie, Sammy, and Lulu want to visit Maya. Oh no! Two houses look the same color. They knock on the wrong door. Mapi is the town map. She gives each house a name. A star. A moon. Not the color. The name! She points by name. This way to Maya. Oh no! Maya's house is closed. Mapi points to the open twin. That is failover. All three friends at the right door. Maya waves. Now you know Mapi! See you next time in Cloud Town, high up in the sky!",
  },
  {
    n: 26,
    title: "Zip",
    tagline: "CloudFront. A copy waits at the edge of town.",
    video: "/26-Zip.mp4?v=cream",
    pdf: "/scripts/26-Zip-script.pdf",
    scriptFile: "26-Zip-script.pdf",
    pages: ["/script-pages/26-Zip-script-p1.jpg"],
    voiceover: "Welcome back to Cloud Town, high up in the sky! Remy lives far away. He wants Maya's new drawing. Sammy walks it all the way across town. Remy waits. And waits. And waits. So slow! The first trip takes forever. Zip is the fast road. Zip keeps a copy at the edge of town, near Remy. Next time Remy asks... it is right there! Instant! Maya paints a new drawing. The old copy goes away. Zip fetches the fresh one. Remy smiles. Maya waves. Now you know Zip! See you next time in Cloud Town, high up in the sky!",
  },
];
